import Home from './Home'
import Detail from './Detail'
import Filter from './Filter'
import Watchlist from './Watchlist'
import UserProfile from './UserProfile'
import AddPost from './AddPost'
import SplashScreen from './SplashScreen'
import Login from './Login'
import Register from './Register'
export {Home,Detail,Filter,Watchlist,UserProfile,AddPost,SplashScreen,Login,Register}